#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math

class Router:

    relations = {}
    sockets = {}
    ports = {}

    def __init__(self, asn, connections):
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        for relationship in connections:
            port, neighbor, relation = relationship.split("-")

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))
            self.ports[neighbor] = int(port)
            self.relations[neighbor] = relation
            # Sends handshake message
            self.send(neighbor, json.dumps({ "type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {}  }))

# Takes oru IP address and asisgns the last integer to 1
    def our_addr(self, dst):
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    def send(self, network, message):
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network]))

    # Send update message to neighbor depending on received route
    def decide_send(self, route, learned_from):
        from_rel = self.relations[learned_from]
        to_rel = self.relations[route]

        if from_rel == 'cust':
            return True
        if from_rel == 'peer' or from_rel == 'prov':
            if to_rel == 'cust':
                return True
            else:
                return False

    def send_update(self, message, srcif):
          # 1. Save a copy of the announcement
        parsed = json.loads(message)
        # 2. Add an entry to your forwarding table
        # 3. Send copies of the announcement to neighboring routers
        self.send(srcif, json.dumps({ "type": "update", "src": self.our_addr(srcif), "dst": srcif, "msg": {parsed["network"], parsed["netmask"], parsed["localpref"], parsed["ASPath"], parsed["origin"], parsed["selfOrigin"]}  }))


    def send_table(self, message, srcif):
            parsed = json.loads(message)
            msg_type = parsed["type"]
            print(f"TYPE: {msg_type}")


            # TO DO: Send table message
            self.send(srcif, json.dumps({ "type": "table", "src": self.our_addr(srcif), "dst": srcif, "msg": {}  }))
            
            
            return
    # def return_route(self, message, srcif):
    #     parsed = json.loads(message)
    #     msg_type = parsed["type"]

    #     if msg_type == "update":
    #         self.send_update(srcif)
    #     if msg_type == "withdraw":
    #         self.send_withdraw(srcif)
    #     if msg_type == "dump":
    #         self.send_table(srcif)
        
    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                k, addr = conn.recvfrom(65535)
                srcif = None
                for sock in self.sockets:
                    if self.sockets[sock] == conn:
                        srcif = sock
                        break
                msg = k.decode('utf-8')
                parsed = json.loads(msg)
                inner_msg = parsed["msg"]
                network = inner_msg["network"]
              #  self.return_route(msg, srcif)
                print(f"MESSAGE: {msg}")
                print(f"INCOMING: {srcif}")
                print(f"INNERMSG: {inner_msg}")
                print(f"NEWORK: {network}")

                print("Received message '%s' from %s" % (msg, srcif))
                
        return

if __name__ == "__main__": 
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()
    


