#!/usr/bin/env python3

import argparse
import socket
import html
from html.parser import HTMLParser
import ssl
import sys

class FakebookParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []
        self.flags = []
        self.csrf = None
        self.in_flag = False

    def handle_starttag(self, tag, attrs):

        # find all links and append it to self.links
        if tag == "a":
            for attr, value in attrs:
                if attr == "href":
                    self.links.append(value)

        # find instance flags and set to true
        if tag == "h3":
            for attr, value in attrs:
                if attr == "class" and value == "secret_flag":
                    self.in_flag = True
        # find the csrfmiddlewaretoken and assign it to self.csrf
        if tag == "input":
            attrs_dict = dict(attrs)
            if attrs_dict.get("name") == "csrfmiddlewaretoken":
                self.csrf = attrs_dict.get("value")

    # if flag exists append it to self.flags
    def handle_data(self, data):
        if self.in_flag:
            stripped = data.strip()
            if stripped.startswith("FLAG: "):
                self.flags.append(stripped[len("FLAG: "):])
            self.in_flag = False

DEFAULT_SERVER = "fakebook.khoury.northeastern.edu"
DEFAULT_PORT = 443

class Crawler:
    def __init__(self, args):
        self.server = args.server
        self.port = args.port
        self.username = args.username
        self.password = args.password

        self.socket = None
        self.cookies = {}
        self.frontier = []
        self.visited = set()
        self.flags = []
    
    def connect(self):
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.connect((self.server, self.port))

        # tls
        context = ssl.create_default_context()
        self.socket = context.wrap_socket(sock, server_hostname=self.server)

    def scrape(self, html):
        parser = FakebookParser()
        parser.feed(html)

        # If link hasn't been visited add it to frontier
        for link in parser.links:
            if self.server in link or link.startswith("/"):
                if link.startswith("http"):
                    link = "/" + "/".join(link.split("/")[3:])
                #skip login/logout
                if not link.startswith("/fakebook/"):
                    continue
                if link not in self.visited:
                    self.frontier.append(link)
        # if flag doesn't already exist, add flag to self.flags
        # double check this
        for flag in parser.flags:
            if flag not in self.flags:
                self.flags.append(flag)

                print(flag)         

    def get_request(self, path, host):
        try:
            request = (
                f"GET {path} HTTP/1.1\r\n"
                f"Host: {host}\r\n"
                f"Cookie: csrftoken={self.cookies.get('csrftoken', '')}; sessionid={self.cookies.get('sessionid', '')}\r\n"
                f"Connection: keep-alive\r\n"
                f"\r\n"
            )
            self.socket.send(request.encode('ascii'))
        except:
            self.connect()
            self.socket.send(request.encode('ascii'))
        return request

    def post_request(self, path, host, token, username, password):
        body = f"username={username}&password={password}&csrfmiddlewaretoken={token}&next=%2Ffakebook%2F"
        request = (
            f"POST {path} HTTP/1.1\r\n"
            f"Host: {host}\r\n"
            f"Content-Type: application/x-www-form-urlencoded\r\n"
            f"Content-Length: {len(body)}\r\n"
            f"Cookie: csrftoken={token}\r\n"
            f"Connection: keep-alive\r\n\r\n"
            f"{body}"
        )
        self.socket.send(request.encode('ascii'))
        return request

    def receive_response(self):
        raw = b""
        while b"\r\n\r\n" not in raw:
            data = self.socket.recv(4096)
            if not data:
                break
            raw += data

        header_bytes, _, body_bytes = raw.partition(b"\r\n\r\n")
        header_text = header_bytes.decode("latin-1")

        content_length = None
        chunked = False
        for line in header_text.split("\r\n"):
            lower = line.lower()
            if lower.startswith("content-length:"):
                content_length = int(line.split(":", 1)[1].strip())
            if lower.startswith("transfer-encoding:") and "chunked" in lower:
                chunked = True

        if content_length is not None:
            while len(body_bytes) < content_length:
                data = self.socket.recv(4096)
                if not data:
                    break
                body_bytes += data
            return header_bytes + b"\r\n\r\n" + body_bytes

        if chunked:
            plain_body = b""
            buf = body_bytes
            while True:
                while b"\r\n" not in buf:
                    more = self.socket.recv(4096)
                    if not more:
                        break
                    buf += more
                size_line, _, buf = buf.partition(b"\r\n")
                chunk_size = int(size_line.split(b";")[0].strip(), 16)
                if chunk_size == 0:
                    break
                while len(buf) < chunk_size + 2:
                    more = self.socket.recv(4096)
                    if not more:
                        break
                    buf += more
                plain_body += buf[:chunk_size]
                buf = buf[chunk_size + 2:]
            return header_bytes + b"\r\n\r\n" + plain_body

        while True:
            data = self.socket.recv(4096)
            if not data:
                break
            body_bytes += data
        return header_bytes + b"\r\n\r\n" + body_bytes

    def parse_response(self, response):
        response_text = response.decode('latin-1')
        response_header = response_text.split('\r\n\r\n')[0]
        response_body = response_text.split('\r\n\r\n')[1]

        status_code = int(response_text.split()[1])

            
        return status_code, response_header, response_body
    def login(self):
        self.get_request("/accounts/login/?next=/fakebook/", self.server)
        response = self.receive_response()
        status_code, response_header, response_body, = self.parse_response(response)
        # print(f"full header:\n{response_header}", file=sys.stderr)
        for l in response_header.split('\r\n'):
            if "set-cookie" in l and "csrftoken=" in l:
                cookie = l.split("csrftoken=")[1].split(";")[0]
                self.cookies['csrftoken'] = cookie
                # print(f"saved csrftoken: {cookie}", file=sys.stderr)

        parser = FakebookParser()
        parser.feed(response_body)
        token = parser.csrf
        # print(f"token: {token}", file=sys.stderr)
        # print(f"cookies before post: {self.cookies}", file=sys.stderr)

        self.post_request('/accounts/login/?next=/fakebook/', self.server, token, self.username, self.password)
        response = self.receive_response()
        status_code, response_header, response_body, = self.parse_response(response) 

        for l in response_header.split('\r\n'):
            if "set-cookie" in l and "sessionid" in l:
                self.cookies['sessionid'] = l.split("sessionid=")[1].split(";")[0]

        # print(f"cookies after post: {self.cookies}", file=sys.stderr)

    def find_flag(self):
        self.frontier.append("/fakebook/")

        while self.frontier and len(self.flags) < 5:
            path = self.frontier.pop()
            self.visited.add(path)
            self.get_request(path, self.server)
            response = self.receive_response()
            status_code, response_header, response_body = self.parse_response(response)

            # Handle status codes
            while status_code == 302:
                for l in response_header.split('\r\n'):
                    if "Location" in l:
                        redirect = l.split(": ")[1].strip()
                        # extract just the path from the URL if absolute
                        if redirect.startswith("http"):
                            redirect = "/" + "/".join(redirect.split("/")[3:])
                        self.get_request(redirect, self.server)
                        response = self.receive_response()
                        status_code, response_header, response_body = self.parse_response(response)
            if status_code == 200:
                self.scrape(response_body)

            if status_code == 403 or status_code == 404:
                pass
            while status_code == 503:
                self.get_request(path, self.server)
                response = self.receive_response()
                status_code, response_header, response_body = self.parse_response(response)

    def run(self):
        self.connect()
        self.login()
        self.find_flag()
        
        # for flag in self.flags:
        #     print(f"FLAG FOUND : " + flag)
       
        # response = self.receive_response()
        # status_code, response_header, response_body = self.parse_response(response)

     
        





if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='crawl Fakebook')
    parser.add_argument('-s', dest="server", type=str, default=DEFAULT_SERVER, help="The server to crawl")
    parser.add_argument('-p', dest="port", type=int, default=DEFAULT_PORT, help="The port to use")
    parser.add_argument('username', type=str, help="The username to use")
    parser.add_argument('password', type=str, help="The password to use")
    args = parser.parse_args()
    sender = Crawler(args)
    sender.run()
