#!/usr/bin/env python3

import socket
import re
import sys
import os        



# Parse the input. Extract the parameters
# Example input: ftp://john:secret123@ftp.example.com/path
def parse_ftp():
    if len(sys.argv) < 2:
        sys.stderr.write("Usage: ./4700ftp [operation] [param1] [param2]")
        sys.exit(1)

    ftp_url = None
    for arg in sys.argv:
        if arg.startswith("ftp://"):
            ftp_url = arg
            break

    if not ftp_url:
        sys.stderr.write("Error: Incorrect FTP URL Format")
        sys.exit(1)

    match = re.search(r'ftp://([^:]+):([^@]+)@([^/]+)', ftp_url)
    if match:
        return match.group(1), match.group(2), match.group(3)

    match = re.search(r'ftp://([^/]+)', ftp_url)
    if match:
        return "anonymous", "", match.group(1)

    sys.stderr.write("Error: Incorrect FTP URL Format")
    sys.exit(1)


# Connect to the FTP server
def control_connect(HOST, PORT):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((HOST, PORT))
    return sock


def multi_line(sock):
    response = b""

    while True:
        data = sock.recv(4096)
        if not data:
            break

        response += data
        lines = response.split(b'\r\n')
        for line in lines:
            match = re.match(rb'^(\d{3}) ', line)
            if match:
                return response.decode('utf-8', errors='ignore')

    return response.decode('utf-8', errors='ignore')


# Helper function used to send commands
def send_command(sock, command):
    sock.send(command.encode() + b"\r\n")
    return multi_line(sock)


def login(sock, username, password):
    response = send_command(sock, f"USER {username}")
    print(f"Server: USER {username}")
    if password:
        response = send_command(sock, f"PASS {password}")
        print(f"Server: PASS {password}")
    return response


# Send PASV command. Open a separate port for data transfer
def pasv_connect(control_sock):
    reply = send_command(control_sock, "PASV")
    print(reply)

    match = re.search(r'\(([^)]+)\)', reply)
    if match:
        inside = match.group(1).split(',')
        ip = '.'.join(inside[0:4])
        port = (int(inside[4]) * 256) + int(inside[5])

        data_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        data_sock.connect((ip, port))
        return data_sock   
    else:
        raise Exception("PASV failed: " + reply)


# Send "TYPE I" 8-bit binary
def set_up(control_sock):
    type_msg = send_command(control_sock, "TYPE I")
    print(type_msg)
    
    mode_msg = send_command(control_sock, "MODE S")
    print(mode_msg)

    stru_msg = send_command(control_sock, "STRU F")
    print(stru_msg)

    return type_msg, mode_msg, stru_msg



# Sends LIST, to list all files in the FTP server
def listf(control_sock, data_sock):
    reply = send_command(control_sock, "LIST")
    print(reply)
    
    buffer = b""
    while True:
        data = data_sock.recv(4096)
        if not data:
            break
        buffer += data

    data_sock.close()
    print(buffer.decode())

    multi_line(control_sock)  # IMPORTANT: read 226


def delete(control_sock, path):
    reply = send_command(control_sock, f"DELE {path}")
    return reply


def create_dir(control_sock, path):
    reply = send_command(control_sock, f"MKD {path}")
    return reply


def remove_dir(control_sock, path):
    print(path)
    reply = send_command(control_sock, f"RMD {path}")
    print(reply)
    return reply


def upload(control_sock, data_sock, local_path, remote_path):
    with open(local_path, 'rb') as f:
        file_data = f.read()

    reply = send_command(control_sock, f"STOR {remote_path}")
    print(reply)

    data_sock.sendall(file_data)
    data_sock.close()

    reply = multi_line(control_sock)  


def download(control_sock, data_sock, path, local_path):
    reply = send_command(control_sock, f"RETR {path}")
    print(reply)

    # Only read data if server said it will send data
    if not reply.startswith("150"):
        data_sock.close()
        return

    with open(local_path, 'wb') as d:
        while True:
            data = data_sock.recv(4096)
            if not data:
                break
            d.write(data)

    data_sock.close()
    reply = multi_line(control_sock)  # read 226
    print(reply)




def read_command(control_sock):

    ftp_url = None
    for arg in sys.argv:
        if arg.startswith("ftp://"):
            ftp_url = arg
            break

    re_path = re.search("^ftp://[^/]+(/.*)$", ftp_url)
    path = re_path.group(1)


    if sys.argv[1] == 'ls':
        set_up(control_sock)
        data_sock = pasv_connect(control_sock)
        listf(control_sock, data_sock)
        
    if sys.argv[1] == 'rm':
        delete(control_sock, path)

    if sys.argv[1] == 'rmdir':
        remove_dir(control_sock, path)

    if sys.argv[1] == 'mkdir':
        create_dir(control_sock, path)

    if sys.argv[1] == 'cp':
        set_up(control_sock)
        data_sock = pasv_connect(control_sock)

        local_path = sys.argv[2]

        if sys.argv[2].startswith("ftp://"):
            download(control_sock, data_sock, path, sys.argv[3])
        else:
            upload(control_sock, data_sock, local_path, path)


    if sys.argv[1] == 'mv':
        set_up(control_sock)
        data_sock = pasv_connect(control_sock)

        if sys.argv[2].startswith("ftp://"):
            download(control_sock, data_sock, path, sys.argv[3])
            delete(control_sock, path)
        else:
            upload(control_sock, data_sock, sys.argv[2], path)
            os.remove(sys.argv[2])



def main():

    user, password, hostname = parse_ftp()

    sock = control_connect(hostname, 21)

    multi_line(sock)  # read hello
    login(sock, user, password)

    read_command(sock)

    send_command(sock, "QUIT")
    sock.close()


if __name__ == "__main__":
    main()
